### ISSUE TITLE
Cannot install noblox.js without issues.

### ISSUE THREAD

**Issue by Dreamurrrr** [suufi/noblox.js#142]
**Describe the bug**
Whenever you try to run `npm install noblox.js --save`, it states that it has "Failed at the noblox.js@4.6.0 postinstall script." This is the error that appears:
```
> noblox.js@4.6.0 postinstall /home/notime/Documents/Visual Studio Code/NutBot/node_modules/noblox.js
> node postinstall.js

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /home/notime/Documents/Visual Studio Code/NutBot/node_modules/noblox.js/postinstall.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/notime/Documents/Visual Studio Code/NutBot/node_modules/noblox.js/postinstall.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/notime/Documents/Visual Studio Code/NutBot/node_modules/noblox.js/postinstall.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! noblox.js@4.6.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noblox.js@4.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/notime/.npm/_logs/2020-06-01T03_15_11_002Z-debug.log
```
I notice it says 
> Error: Cannot find module 'chalk'

So after running `npm install chalk` and `npm install noblox.js --save`, this next error occurs:
```
> noblox.js@4.6.0 postinstall /home/notime/Documents/Visual Studio Code/NutBot/node_modules/noblox.js
> node postinstall.js

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'figlet'
```
After installing chalk and figlet, I was able to install noblox.js.

**To Reproduce**
1. Run `npm install noblox.js --save`
2. See error

**Expected behavior**
A nice clean install without any errors.

**Why this Issue is Important**
This issue is important because these errors can deter new people (newbies) from installing noblox.js. If a young person decides to start coding and does not have the skills to troubleshoot these errors, he/she may just call it quits. This can even deter people from starting to code at all. We all started out at the same level as newbies, so making it easier will deter less new people.

**Additional Information**
These errors also happen when running `npm install noblox.js`.

**Comment by MutantRabbit767** [comment]
suprisingly ive been trying to install forever but i have finally done it and you need
figlet
chalk

**Comment by Dreamurrrr** [comment]
> suprisingly ive been trying to install forever but i have finally done it and you need
> figlet
> chalk
Bruh

**Comment by MutantRabbit767** [comment]
did you not have this problem?

**Comment by Dreamurrrr** [comment]
I was referring to #143. Also the deprecation of cookieLogin means that some other function has superceded it.

**Comment by Dreamurrrr** [comment]
@MutantRabbit767 I was referring to #143. Also the deprecation of cookieLogin means that some other function has superceded it.

**Comment by MutantRabbit767** [comment]
superceded? sorry im new to this.

**Comment by Dreamurrrr** [comment]
@MutantRabbit767 meaning that cookieLogin has been replaced by a better function.

**Comment by Dreamurrrr** [comment]
Use `setCookie` and `refreshCookie` instead of `cookieLogin`, @MutantRabbit767.

**Comment by MutantRabbit767** [comment]
ok thanks :)

**Comment by Neztore** [comment]
Fixed by #141

**Comment by Dreamurrrr** [comment]
@Neztore was an update pushed out yet? The issue still persists on my end.
